config/routes.rb
Shotspace::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :bookings

  mount Soulmate::Server, :at => '/sm'

  get "omniauth_callbacks/vkontakte"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :photos

  resources :categories

  get "pages/welcome" => "pages#welcome"
  get "pages/promo" => "pages#promo"
  get "autocomplete" => "pages#autocomplete", :as => 'autocomplete'
  get "profile" => "users#profile"

  get 'users/:id/booking' => "users#booking", :as => 'user_booking'
  get 'users/:id/photos' => "users#photos", :as => 'user_photos'
  get 'users/:id/upload' => "users#upload", :as => 'user_upload'
  get 'my/bookings' => "users#bookings", :as => 'my_bookings'
  
  get 'not_found' => 'pages#not_found', as: :not_found

  resources :cities
  resources :users

  resources :cities do
    collection do
      get 'autocomplete'
    end
  end

  resources :cities do
    resources :categories do
      resources :users
    end
  end

  root 'pages#welcome'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:vkontakte]

  belongs_to :region
  belongs_to :city
  has_many :photos
  has_many :user_categories
  has_many :categories, :through => :user_categories
  has_many :bookings

  def city_name
    city && city.name
  end

  def city_name=(value)
    self.city = City.find_by_name(value)
    self.city ||= City.new(:name => value)
  end


  def self.find_for_vkontakte_oauth access_token
    if user = User.where(url: access_token.info.urls.Vkontakte).first
      user
    else
      User.create!(provider: access_token.provider,
          url: access_token.info.urls.Vkontakte,
          username: access_token.info.name,
          nickname: access_token.uid,
          email: access_token.uid.to_s + '@vk.com',
          password: Devise.friendly_token[0,20]) 
    end
  end
  
  validates_each :photos do |user, attr, value|
    user.errors.add attr, "Не более 100 изображений для одного пользователя" if user.photos.size >= 101
  end
  
  NUM_REGEX = /\A[0-9]+\z/ || //

  validates :email, :presence => true, 
                    :length => {:maximum => 50},
                    :uniqueness => true,
                    :format => {:with => /@/}
  validates :username, :length => {:maximum => 50}
  validates :phone, :length => {:maximum => 20}
  validates :website, :length => {:maximum => 30}
  validates :dayprice, :length => {:maximum => 7}
  validates :hourprice, :length => {:maximum => 7}

  def photos_array=(array)
    array.each do |file|
      photos.build(:image => file)
    end
  end

  has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "145x145#", :micro => "50x50#" }, :default_url => "/assets/missing-avatar.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  # message after signup
  after_create :send_admin_mail
  def send_admin_mail
    UserMailer.new_user_message(self).deliver
  end

  private

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def vkontakte
  	@user = User.find_for_vkontakte_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout :choose_layout
  around_filter :catch_not_found

  def index
    @search = User.order('created_at DESC').search(params[:q])
    @users = @search.result.page(params[:page]).per_page(10)
  end

  def show
    @user = User.find(params[:id])
    @photos = @user.photos.page(params[:page]).per_page(6)
    respond_to do |format|
      format.html
      format.js # add this line for your js template
    end
  end
  
  def photos
    @user = User.find(params[:id])
    @photos = @user.photos
  end

  def profile
    @user = current_user
  end
  
  def upload
    if current_user
      @user = current_user
      @photos = @user.photos
    else
      redirect_to not_found_path
    end
  end
  
  def booking
    @booking = Booking.new
  end

  def bookings
    if current_user 
      @bookings = Booking.where(:user_id => current_user)
    else
      redirect_to not_found_path
    end
  end

  def edit
    if current_user
  	  @user = current_user
    else
      redirect_to not_found_path
    end

    def get_drop_down_options
      val = params[:region]
      #Use val to find records
      options = City.collect{|x| "'#{x.id}' : '#{x.label}'"}    
      render :text => "{#{options.join(",")}}" 
    end
  end
  
  def update
    @user = current_user 
    if user_params[:password].blank?
      user_params.delete :password
      user_params.delete :password_confirmation
    end
    
    if @user.update(user_params)
      sign_in @user, :bypass => true
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :current_password, :nickname, :provider, :url, :avatar, :daterange, :website, :city_name, :city_id, :region_id, :phone, :dayprice, :hourprice, :photos_array => [], :category_ids => [])
    end

    def needs_password?(user, params)
      params[:password].present?
    end

    def after_update_path_for(resource)
      user_path(current_user)
    end

    def choose_layout
      case action_name
      when 'show'
        'user'
      when 'edit'
        'user_edit'
      when 'index', 'booking', 'bookings', 'upload'
        'index'
      when 'photos'
        'photos'
      else
        'application'
      end
    end

    def catch_not_found
      yield
    rescue ActiveRecord::RecordNotFound
      redirect_to not_found_path
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def range
    [@user.daterange.gsub(',', '\', \'').gsub(/\A/, '\'').gsub(/\z/, '\'').html_safe]
  end
end

app/views/users/_photos.html.haml
- @photos.each do |photo|
  %li
    = link_to(image_tag(photo.image.url(:square)), image_path(photo.image.url(:original)), :class => 'box', :rel => 'group')

app/views/users/_user.html.haml
.col-lg-3.col-md-3.col-sm-4.col-xs-12.user-in-list
  = image_tag user.avatar.url(:thumb)
  %h2 
    = link_to (user.username || "Безымянный фотограф"), user
  - if user.city
    %span.city-muted #{user.city.name}
  - else
    %span.city-muted Город N
  %p.list-price
    %b от #{user.hourprice  || "0"} рублей в час
  

app/views/users/booking.html.haml
.container
  %p#notice
    = notice
  %h2 Бронирование фотографа
  = simple_form_for(@booking) do |f|
    = f.error_notification
    = f.hidden_field :user_id, :value => params[:id]
    .alert.alert-warning Обратите внимание, что в указанную на странице фотографа цену входят только услуги самого фотографа. Другие услуги (например аренда студии или услуги визажиста оплачиваются отдельно).
    .row
      .form-inputs.col-lg-4
        .form-group
          %label Ваше имя
          = f.text_field :name, :required => true, :autofocus => true, :class => 'form-control'
        .form-group
          %label Электронная почта
          = f.text_field :email, :required => true, :autofocus => true, :class => 'form-control', :type => 'email'
        .form-group
          %label Телефон
          = f.text_field :phone, :required => true, :autofocus => true, :class => 'form-control'
        .form-group
          %label Выберите день или дни, в которые вам нужны услуги фотографа
          .input-group.date
            = f.text_field :daterange, :class => 'form-control'
            %span.input-group-addon
              %i.glyphicon.glyphicon-th
          :javascript
            $(function() {
              $('.input-group.date').datepicker({
                  orientation: "auto left",
                  multidate: true,
                  todayHighlight: true,
                  format: "'dd/mm/yyyy'"
              });
            });
        .form-group
          %label Подробная информация о вашем заказе (количество часов и так далее)
          = f.text_area :additional, :required => true, :autofocus => true, :class => 'form-control'
        .form-group
          %label Вы не робот? #{@booking.humanizer_question}
          = f.text_field :humanizer_answer, :class => 'form-control'
          = f.hidden_field :humanizer_question_id
        .form-group
          = f.button :submit, "Отправить", :class => 'btn btn-success'

app/views/users/bookings.html.haml
.container
  %h2 Мои заявки
  %p Заявки на бронирование ваших услуг отправленные клиентами
  .table-responsive
    %table.table.table-striped
      %tr 
        %th Имя
        %th Время отправки
        %th Почта
        %th Телефон
        %th Даты бронирования
        %th Дополнительно
      - @bookings.each do |booking|
        %tr
          %td
            %p #{link_to booking.name, booking}
          %td
            %p #{booking.created_at}
          %td
            %p #{booking.email}
          %td
            %p #{booking.phone}
          %td
            %p #{booking.daterange}
          %td
            %p #{booking.additional}
  
      

app/views/users/edit.html.haml
.container
  .profile
    %h1 Редактирование профиля
    = simple_form_for(@user) do |f|
      - if @user.errors.any?
        #error_explanation
          %h2
            = pluralize(@user.errors.count, "error")
            prohibited this region from being saved:
          %ul
            - @user.errors.full_messages.each do |msg|
              %li= msg
      .row
        .col-lg-4.col-sm-12.col-xs-12
          .form-group
            %label Имя и фамилия
            = f.text_field :username, :class => 'form-control'
          .form-group.city-name
            %label Город
            = f.text_field :city_name, :class => 'form-control'
          .form-group
            %label Телефон
            = f.text_field :phone, :class => 'form-control'
          .form-group
            %label Электронная почта
            = f.text_field :email, :class => 'form-control'
          .form-group
            %label Цена за день работы
            = f.number_field :dayprice, :class => 'form-control'
          .form-group
            %label Цена за час работы
            = f.number_field :hourprice, :class => 'form-control'
          .form-group
            %label Рабочий календарь (отметьте дни в которые вы заняты)
            .input-group.date
              = f.text_field :daterange, :class => 'form-control'
              %span.input-group-addon
                %i.glyphicon.glyphicon-th
            :javascript
              $(function() {
                $('.input-group.date').datepicker({
                    orientation: "auto left",
                    multidate: true,
                    todayHighlight: true,
                    format: "'dd/mm/yyyy'"
                });
              });
          .form-group
            %label Жанры в которых вы работаете
            .form-group
            - Category.all.each do |category|
              %ul.list-inline
                %li
                  %p
                    = check_box_tag "user[category_ids][]", category.id, @user.category_ids.include?(category.id)
                    = category.name
          .form-group
            = f.input :avatar, as: :file, label: 'Аватар'
          .form-group
            Загружен #{image_tag @user.avatar.url(:micro), :class => 'img-thumbnail load-avatar'}
          .form-group
            .actions
              = f.submit 'Сохранить', class: 'btn btn-default'
:coffeescript
  $('input#user_city_name').typeahead({
    remote: '/autocomplete?term=%QUERY'
  });

  $('input').keyup ->
    $(this).val($(this).val().substr(0, 1).toUpperCase() + $(this).val().substr(1).toLowerCase())

app/views/users/index.html.haml
.container
  .users-result
    %h1 Все пользователи
    = search_form_for @search, :html => {:class => "form-inline"} do |f|
      .form-group
        = text_field_tag :city_id, params[:city_id], :class => 'form-control', :placeholder => 'Название города'
      .form-group
        = f.hidden_field :city_id_eq
      .form-group
        .actions
          = f.submit "Найти", :class => 'btn btn-default'
    %hr
  .row.user-preview
    #users
      = render @users
  = will_paginate @users
:coffeescript
  $('input#city_id').typeahead({
    remote: '/autocomplete?term=%QUERY'
  });
  
  $("input#city_id").on "typeahead:selected", (object, datum) ->
    $("input#q_city_id_eq").val(datum.link)

  # set caret active
  $(document).ready ->
    $("input#city_id").focus()

  $('input').keyup ->
    $(this).val($(this).val().substr(0, 1).toUpperCase() + $(this).val().substr(1).toLowerCase())
  
  

app/views/users/index.js.haml
$('#users').append('#{j render(@users)}');
- if @users.next_page
  $('.pagination').replaceWith('#{j will_paginate(@users)}');
- else
  $('.pagination').remove();
- sleep 1

app/views/users/photos.html.haml
- if @photos.present?
  .portfolio_container.photos_page
    .portfolio_preview
      - @user.photos.order('created_at DESC').each do |photo|
        .portfolio_item
          = link_to(image_tag(photo.image.url(:medium)), image_path(photo.image.url(:original)), :class => 'box', :rel => 'group')
- else
  .scroll_dummy
    %p Пользователь не загрузил ни одной фотографии
:javascript

  var $container = $('.portfolio_preview');
  $container.imagesLoaded(function(){
    $container.masonry({
      // options
      itemSelector : '.portfolio_item'
    });
  });

  $(document).ready(function() {
    $(function(){
        $('.box').touchTouch();
    });
  });

app/views/users/show.html.haml
.container
  %p#notice
    = notice
  .profile
    .row
      .col-lg-6.col-md-12
        %h1 #{@user.username || 'Имя не указано'}
      .col-lg-6.col-md-12
        - if @user == current_user
        - else
          %script{charset: "utf-8", src: "//yandex.st/share/share.js", type: "text/javascript"}
          .yashare-auto-init{"data-yasharel10n" => "ru", "data-yasharequickservices" => "vkontakte,facebook,twitter,odnoklassniki", "data-yasharetheme" => "counter"}
    .row
      .col-lg-8.col-sm-8.about
        %div
          .row
            .col-lg-4.avatar-container
              = image_tag @user.avatar.url(:thumb)
            .col-lg-8.about-data
              - if @user.city
                .span.glyphicon.glyphicon-map-marker
                = link_to @user.city.name, @user.city
              - else
                .span.glyphicon.glyphicon-map-marker
                = link_to "Город N", root_path
              - if @user.categories.present?
                .tagline
                - @user.categories.each do |category|
                  .label-tag
                    = category.name
              - else
                .tagline
                  .label-tag Категории пока не указаны
              %p.profile-contact
                %span.text-muted Телефон:&nbsp;
                = @user.phone || "не заполнено"
                &nbsp;
                %span.text-muted Сайт:&nbsp;
                = @user.website || "не заполнено"
      .col-sm-4.col-lg-4
        %table.book-column
          %tr
            %td
              - if @user != current_user
                = link_to "Забронировать", user_booking_path, :class => 'btn btn-success book-button'
          %tr
            %td
              %p.profile-price
                от 
                %b
                  #{@user.hourprice || "100"}
                руб. / час
              %p.text-muted от #{@user.dayprice || "200"} руб. / день
- if @photos.present?
  %ul.cbp-rfgrid
    = render :partial => 'photos'
  .load_more
    = link_to 'Показать больше фотографий', user_path(:page => @photos.next_page), :class => 'load-more-photos', :remote => true if @photos.next_page
- else
  .scroll_dummy
    %p Пока не загружено ни одной фотографии
    - if @user == current_user
      = link_to "Загрузить", user_upload_path, :class => 'btn btn-default btn-upload-empty'
.calendar-block
  .container
    %h2 Рабочий календарь
    .calendar_show
      .shield
:javascript
  $(function() {
      $('.calendar_show').datepicker('setDates', [#{@user.daterange}]).datepicker('language', 'ru');
  });

  $(document).ready(function(){
      $('body').on('mousedown', ".box", function (){
        $('.placeholder').remove();
        $('.box').touchTouch();
      });

  });
  

app/views/users/show.js.haml
$('.cbp-rfgrid').append('#{j render partial: 'photos'}');
$('a.load-more-photos').attr('href', '#{user_path page: @photos.next_page}');
 
- unless @photos.next_page
  $('.load_more').remove();

app/views/users/upload.html.haml
.container
  .profile
    %h1 Управление фотографиями
    %p Загрузка изображений, максимальный размер одного файла 10мб, не более 10 файлов за 1 раз
    #filelist Your browser doesn't have Flash, Silverlight or HTML5 support.
    #console
    %br/
    #container.uploader-ui
      %a#pickfiles.btn.btn-primary{href: "javascript:;"} Выбрать файлы
      %a#uploadfiles.btn.btn-success{href: "javascript:;"} Загрузить
    %br/
    .row.image-control
      - @user.photos.order('created_at DESC').each do |photo|
        .col-sm-3.col-lg-3.column.ui-sortable.preview-thumb
          = link_to "x", photo, method: :delete, data: {confirm: "Are you sure?"}, :class => 'destroyer'
          = image_tag photo.image.url(:thumb), :class => 'uploader-img'
:javascript
  var token = $( 'meta[name="csrf-token"]' ).attr( 'content' );
  var uploader = new plupload.Uploader({
      runtimes : 'html5,flash,silverlight,html4',
       
      browse_button : 'pickfiles', // you can pass in id...
      container: document.getElementById('container'), // ... or DOM Element itself
       
      url : '/photos',
      multipart : true,
      multipart_params : {
        '#{request_forgery_protection_token}': '#{form_authenticity_token}',
        '#{Rails.application.config.session_options[:key]}': '#{request.session_options[:id]}'
      },

      filters : {
          max_file_size : '10mb',
          mime_types: [
              {title : "Image files", extensions : "jpg,gif,png"},
              {title : "Zip files", extensions : "zip"}
          ]
      },
      resize: {
        width: 900,
        height: 600
      },
      // Flash settings
      flash_swf_url : 'http://rawgithub.com/moxiecode/moxie/master/bin/flash/Moxie.cdn.swf',
   
      // Silverlight settings
      silverlight_xap_url : 'http://rawgithub.com/moxiecode/moxie/master/bin/silverlight/Moxie.cdn.xap',
       
   
      init: {
          PostInit: function() {
              document.getElementById('filelist').innerHTML = '';
   
              document.getElementById('uploadfiles').onclick = function() {
                  uploader.start();
                  return false;
              };
          },
   
          FilesAdded: function(up, files) {
              plupload.each(files, function(file) {
                  document.getElementById('filelist').innerHTML += '<div id="' + file.id + '">' + file.name + ' (' + plupload.formatSize(file.size) + ') <b></b></div>';
              });
          },
   
          UploadProgress: function(up, file) {
              document.getElementById(file.id).getElementsByTagName('b')[0].innerHTML = '<span>' + file.percent + "%</span>";
          },
   
          Error: function(up, err) {
              document.getElementById('console').innerHTML += "\nError #" + err.code + ": " + err.message;

          }
      }
  });

  uploader.bind('UploadComplete', function() {
      if (uploader.files.length == (uploader.total.uploaded + uploader.total.failed)) {
          $.ajax({
              url: "",
              context: document.body,
              success: function(s,x){
                  $(this).html(s);
              }
          });
          $("#console").html('Файлы успешно загружены');
      }
  });

  uploader.bind('FilesAdded', function(up, files) {
      if(up.files.length > 10 || uploader.files.length > 10 || files.length > 10)
      {
          $("#console").html('Можно загружать не более 10 файлов за один раз');
          return false;
      }
  });
   
  uploader.init();