config/routes.rb
Shotspace::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :bookings

  mount Soulmate::Server, :at => '/sm'

  get "omniauth_callbacks/vkontakte"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :photos

  resources :categories

  get "pages/welcome" => "pages#welcome"
  get "pages/promo" => "pages#promo"
  get "autocomplete" => "pages#autocomplete", :as => 'autocomplete'
  get "profile" => "users#profile"

  get 'users/:id/booking' => "users#booking", :as => 'user_booking'
  get 'users/:id/photos' => "users#photos", :as => 'user_photos'
  get 'users/:id/upload' => "users#upload", :as => 'user_upload'
  get 'my/bookings' => "users#bookings", :as => 'my_bookings'
  
  get 'not_found' => 'pages#not_found', as: :not_found

  resources :cities
  resources :users

  resources :cities do
    collection do
      get 'autocomplete'
    end
  end

  resources :cities do
    resources :categories do
      resources :users
    end
  end

  root 'pages#welcome'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :region
  has_many :users
  has_many :categories

  after_save :add_to_soulmate
  before_destroy :remove_from_soulmate

  private

  def add_to_soulmate
    loader = Soulmate::Loader.new("city")
    loader.add("term" => name, "id" => self.id, "data" => { "region" => region_id})
  end

  def remove_from_soulmate
    loader = Soulmate::Loader.new("city")
    loader.remove("id" => self.id)
  end

  def self.search(term)
    cities = Soulmate::Matcher.new("city").matches_for_term(term)
    cities.collect { |c| { "link" => c["id"], "value" => c["term"], "region" => c["data"]["region"] } }
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]
  layout :choose_layout


  def show
    @search = User.where(:city_id => @city).order('created_at DESC').search(params[:q])
    @users = @search.result.page(params[:page]).per_page(10)
    @categories = Category.all
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    def choose_layout
      case action_name
      when 'show'
        'index'
      else
        'application'
      end
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :region_id %><br>
    <%= f.number_field :region_id %>
  </div>
  <div class="field">
    <%= f.label :country_id %><br>
    <%= f.number_field :country_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Region</th>
      <th>Country</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.user_id %></td>
        <td><%= city.region_id %></td>
        <td><%= city.country_id %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.haml
.container
  .users-result
    %h1 #{@city.name}
  - if @city.users.present?
    Подобрать фотографа
    .btn-group.category-dropdown
      %button.btn.btn-default
        По типу съемки:
      %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
        
        %span.caret
      %ul.dropdown-menu{role: 'menu'}
        - @categories.each do |category|
          %li #{link_to category.name, [@city, category]}
    %hr
    .row.user-preview
      #users
        = render @users
    = will_paginate @users
  - else
    %p.nobody В этом городе пока никто не зарегистрирован. Вы фотограф? #{link_to 'Будьте первым в своем городе!', new_user_registration_path}
:javascript

  $(document).ready(function() {
    $(function(){
        $('.box').touchTouch();
    });
  });
  