config/routes.rb
Shotspace::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :bookings

  mount Soulmate::Server, :at => '/sm'

  get "omniauth_callbacks/vkontakte"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :photos

  resources :categories

  get "pages/welcome" => "pages#welcome"
  get "pages/promo" => "pages#promo"
  get "autocomplete" => "pages#autocomplete", :as => 'autocomplete'
  get "profile" => "users#profile"

  get 'users/:id/booking' => "users#booking", :as => 'user_booking'
  get 'users/:id/photos' => "users#photos", :as => 'user_photos'
  get 'users/:id/upload' => "users#upload", :as => 'user_upload'
  get 'my/bookings' => "users#bookings", :as => 'my_bookings'
  
  get 'not_found' => 'pages#not_found', as: :not_found

  resources :cities
  resources :users

  resources :cities do
    collection do
      get 'autocomplete'
    end
  end

  resources :cities do
    resources :categories do
      resources :users
    end
  end

  root 'pages#welcome'

end

app/views/layouts/_footer.html.haml
.footer
  %p &copy; Shotspace.ru, поиск и бронирование фотографов
  %ul.list-inline
    %li
      = link_to 'Вход', new_user_session_path
    %li
      = link_to 'Регистрация', new_user_registration_path

app/views/layouts/_metrika.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter24121417 = new Ya.Metrika({id:24121417,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/24121417" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="back">
		<a href="/"><img src="/assets/logo-nav.svg"></a>
	  </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to 'Заявки', my_bookings_path %></li>
        <li><%= link_to 'Мой профиль', user_path(current_user) %></li>
        <li><%= link_to 'Настройки профиля', edit_user_path(current_user) %></li>
        <li><%= link_to 'Загрузка фотографий', user_upload_path(current_user) %></li>
        <li><%= link_to 'Аккаунт', edit_user_registration_path(current_user) %>
		    <li><%= link_to 'Выйти', destroy_user_session_path, :method => :delete %></li>
	    <% else %>
      <li><%= link_to 'Все фотографы', users_path %></li>
			<li><%= link_to 'Вход', new_user_session_path %></li>
			<li><%= link_to 'Регистрация', new_user_registration_path %></li>
		<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_oauth_warning.html.haml
- if user_signed_in? && current_user.email =~ /(vk.com)/
  .oauth-warning
    Рекомендуем #{link_to "указать адрес", edit_user_path(current_user)} электронной почты, чтобы принимать заявки от пользователей

app/views/layouts/_user_status.html.erb
<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p>
  <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width">
  <title>Shotspace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/oauth_warning' %>
<%= render 'layouts/navbar' %>
<%= yield %>
<%= render 'layouts/footer' %>
<script type="text/javascript">
$(document).ready(function() {
	if(!Modernizr.svg){
	    $('img[src*="svg"]').attr('src', function() {
		return $(this).attr('src').replace('.svg', '.png');
	    });
	}
});
</script>
<%= render 'layouts/metrika' %>
</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width">
  <meta Http-Equiv="Cache-Control" Content="no-cache">
  <meta Http-Equiv="Pragma" Content="no-cache">
  <meta Http-Equiv="Expires" Content="0"> 
  <title>Shotspace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/oauth_warning' %>
<%= render 'layouts/navbar' %>
<%= yield %>
<script type="text/javascript">
$(document).ready(function() {
	if(!Modernizr.svg){
	    $('img[src*="svg"]').attr('src', function() {
		return $(this).attr('src').replace('.svg', '.png');
	    });
	}
});
</script>

<%= render 'layouts/metrika' %>
</body>
</html>

app/views/layouts/photos.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width">
  <title>Shotspace</title>
  <%= stylesheet_link_tag    "bootstrap.min", "style", "touchTouch", "datepicker-show", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color:#000;">
<%= render 'layouts/oauth_warning' %>
<%= render 'layouts/navbar' %>
<%= yield %>
<script type="text/javascript">
$(document).ready(function() {
	if(!Modernizr.svg){
	    $('img[src*="svg"]').attr('src', function() {
		return $(this).attr('src').replace('.svg', '.png');
	    });
	}
});
</script>
<%= render 'layouts/metrika' %>
</body>
</html>

app/views/layouts/promo.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width">
  <title>Ты фотограф? Получи в подарок iPhone 5S!</title>
  <meta name="description" content="Хочешь iPhone 5S? Ты можешь легко получить его">
  <%= stylesheet_link_tag    "bootstrap.min", "style", media: "all", "data-turbolinks-track" => true %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" type="text/javascript"></script>
  <%= javascript_include_tag "bootstrap.min", "typeahead.min", "modernizr-latest.js","data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/oauth_warning' %>
<%= render 'layouts/navbar' %>
<%= yield %>
<script type="text/javascript">
$(document).ready(function() {
	if(!Modernizr.svg){
	    $('img[src*="svg"]').attr('src', function() {
		return $(this).attr('src').replace('.svg', '.png');
	    });
	}
});
</script>
<%= render 'layouts/metrika' %>
</body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width">
  <meta Http-Equiv="Cache-Control" Content="no-cache">
  <meta Http-Equiv="Pragma" Content="no-cache">
  <meta Http-Equiv="Expires" Content="0"> 
  <title>Фотограф <%= @user.username %>, <%= @user.city.name if @user.city %>, заказать, портфолио, цены</title>
  <%= stylesheet_link_tag    "bootstrap.min", "style", "touchTouch", "datepicker-show", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery", "jquery_ujs", "bootstrap.min","bootstrap-datepicker", "imagesloaded.pkgd.min", "modernizr-latest", "touchTouch.jquery", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/oauth_warning' %>
<%= render 'layouts/navbar' %>
<%= yield %>
<%= render 'layouts/footer' %>
<script type="text/javascript">
$(document).ready(function() {
	if(!Modernizr.svg){
	    $('img[src*="svg"]').attr('src', function() {
		return $(this).attr('src').replace('.svg', '.png');
	    });
	}
});
</script>
<%= render 'layouts/metrika' %>
</body>
</html>

app/views/layouts/user_edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width">
  <title>Shotspace</title>
  <%= stylesheet_link_tag    "bootstrap.min", "style", "touchTouch", "datepicker", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/oauth_warning' %>
<%= render 'layouts/navbar' %>
<%= yield %>
<%= render 'layouts/footer' %>
<script type="text/javascript">
$(document).ready(function() {
	if(!Modernizr.svg){
	    $('img[src*="svg"]').attr('src', function() {
		return $(this).attr('src').replace('.svg', '.png');
	    });
	}
});
</script>
<%= render 'layouts/metrika' %>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width">
  <title>Онлайн бронирование фотографов, портфолио, найти фотографа - Shotspace.ru</title>
  <%= stylesheet_link_tag "bootstrap.min", "style", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/oauth_warning' %>
<%= render 'layouts/navbar' %>
<%= yield %>
<script type="text/javascript">
$(document).ready(function() {
	if(!Modernizr.svg){
	    $('img[src*="svg"]').attr('src', function() {
		return $(this).attr('src').replace('.svg', '.png');
	    });
	}
});
</script>
<%= javascript_include_tag "http://api-maps.yandex.ru/1.1/index.xml?key=AAh3IVMBAAAAEtf9PgQAQYS59cC5tf_xqkAvdKRHA032nZAAAAAAAAAAAACcsZXY3HmackiOaRu0rkkYv5R5ew==" %>
<script>
if (YMaps.location) {
	var city = YMaps.location.city
	$('p.target').append('<p class="target">Похоже ваш город ' + city + '? <a href="" class="target-link">Найти фотографа в городе ' + city + '</a>');
	$('a.target-link').on('click', function(e) {
		e.preventDefault();
		$.getJSON( "/autocomplete?term=" + city, function( data ) {
			if (data.length) {
			  window.location = 'cities/' + data[0].link
			} else {
			  $('p.target').html('<p class="target">К сожалению, в этом городе никто не зарегистрирован</p>');
			}
		});
	});
}
else {
    /*something*/
}
</script>
<%= render 'layouts/metrika' %>
</body>
</html>